import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { Toaster } from "sonner";
import { Appbar } from "@/components/Appbar";
import Footer from "@/components/Footer";
import AppWalletProvider from "@/components/AppWalletProvider";


type ToasterProps = React.ComponentProps<typeof Toaster>;
const toastOptions: ToasterProps = {
  theme: "dark",
  richColors: true,
  closeButton: true,
  pauseWhenPageIsHidden: true,
};
const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "muSpace",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased w-full`}
      >
        <AppWalletProvider>

          <Toaster {...toastOptions} />
          <Appbar />

          {children}
          <Footer />
        </AppWalletProvider>
      </body>
    </html>
  );
}
